# Generated by Django 6.1 on 2026-08-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='template_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
