# Generated by Django 6.1 on 2026-08-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('pending', 'На перевірці'), ('approved', 'Прийнято'), ('rejected', 'Відхилено')], default='pending', max_length=20),
        ),
    ]
