# Generated by Django 6.1 on 2026-08-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_newsitem_author_newsitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
