# Generated by Django 6.1 on 2026-08-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0007_profile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gradient_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='primary_color',
            field=models.CharField(default='#0d6efd', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('light', 'Світла'), ('dark', 'Темна')], default='light', max_length=10),
        ),
    ]
