# Generated by Django 6.1 on 2026-08-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0008_profile_gradient_enabled_profile_primary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='secondary_color',
            field=models.CharField(default='#6f42c1', max_length=7),
        ),
    ]
