# Generated by Django 6.1 on 2026-08-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0009_profile_secondary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='category',
            field=models.CharField(choices=[('updates', 'Оновлення сервісу'), ('features', 'Нові функції'), ('tips', 'Поради'), ('templates', 'Шаблони резюме')], default='updates', max_length=20),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='status',
            field=models.CharField(choices=[('published', 'Опубліковано'), ('draft', 'Чернетка')], default='published', max_length=12),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='accent_color',
            field=models.CharField(default='#dc3545', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='background_color',
            field=models.CharField(default='#f8f9fa', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='gradient_direction',
            field=models.CharField(choices=[('90deg', 'Зліва направо'), ('135deg', 'Діагональ'), ('180deg', 'Зверху вниз'), ('270deg', 'Справа наліво')], default='135deg', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('light', 'Світла'), ('dark', 'Темна'), ('system', 'Системна')], default='light', max_length=10),
        ),
    ]
