# Generated by Django 6.1 on 2026-09-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0013_profile_light_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='custom_sections',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
